port: "8000"
smtp:
  port: "587"
  host: "smtp.gmail.com"
  gmail: "giftstochildren@gmail.com"
  password: "jknj qhgv strt iuts"
db:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "genatasks777"
  dbname: "postgres"
  sslmode: "disable"